name: Lint
on: [pull_request]
jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install
        run: "pnpm install"

      - name: Lint step
        run: "pnpm run lint"
